### 

@base = http://localhost:5001

GET {{base}}/puzzles/archive HTTP/1.1


### Create a new puzzle

POST {{base}}/puzzles HTTP/1.1
Content-Type: application/json

{
  "categories": [
    {
      "name": "Famous Scientists",
      "words": [
        {
          "text": "Newton"
        },
        {
          "text": "Einstein"
        },
        {
          "text": "Curie"
        },
        {
          "text": "Darwin"
        }
      ]
    },
    {
      "name": "Capital Cities",
      "words": [
        {
          "text": "London"
        },
        {
          "text": "Paris"
        },
        {
          "text": "Tokyo"
        },
        {
          "text": "Berlin"
        }
      ]
    },
    {
      "name": "Programming Languages",
      "words": [
        {
          "text": "C#"
        },
        {
          "text": "Python"
        },
        {
          "text": "JavaScript"
        },
        {
          "text": "Rust"
        }
      ]
    },
    {
      "name": "Musical Instruments",
      "words": [
        {
          "text": "Guitar"
        },
        {
          "text": "Piano"
        },
        {
          "text": "Violin"
        },
        {
          "text": "Drums"
        }
      ]
    }
  ]
}


### Get all puzzles (admin overview)

GET {{base}}/puzzles HTTP/1.1
Accept: application/json


### Get a single puzzle (replace 1 with actual id)

GET {{base}}/puzzles/9 HTTP/1.1
Accept: application/json


### Delete a puzzle (replace 3 with id)

DELETE {{base}}/puzzles/12 HTTP/1.1


### Get today's daily puzzle

GET {{base}}/puzzles/daily HTTP/1.1


### Submit a guess (replace 8 with puzzle id)

POST {{base}}/puzzles/9/guess HTTP/1.1
Content-Type: application/json

{
  "words": [
    "Piano",
    "Drums",
    "Violin",
    "Guitar"
  ]
}


### 

POST {{base}}/puzzles HTTP/1.1
Content-Type: application/json

{
  "categories": [
    {
      "name": "",
      "words": [
        {
          "text": ""
        }
      ]
    }
  ]
}
