// <auto-generated />
using System;
using Connecions.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Connections.Api.Migrations
{
    [DbContext(typeof(ConnectionsContext))]
    [Migration("20260507163435_AddWord")]
    partial class AddWord
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.7");

            modelBuilder.Entity("Connecions.Api.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("PuzzleId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("PuzzleId");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("Connecions.Api.Models.Puzzle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly?>("LastUsed")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Puzzles");
                });

            modelBuilder.Entity("Connecions.Api.Models.Word", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("CategoryId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Words");
                });

            modelBuilder.Entity("Connecions.Api.Models.Category", b =>
                {
                    b.HasOne("Connecions.Api.Models.Puzzle", null)
                        .WithMany("Categories")
                        .HasForeignKey("PuzzleId");
                });

            modelBuilder.Entity("Connecions.Api.Models.Word", b =>
                {
                    b.HasOne("Connecions.Api.Models.Category", null)
                        .WithMany("Words")
                        .HasForeignKey("CategoryId");
                });

            modelBuilder.Entity("Connecions.Api.Models.Category", b =>
                {
                    b.Navigation("Words");
                });

            modelBuilder.Entity("Connecions.Api.Models.Puzzle", b =>
                {
                    b.Navigation("Categories");
                });
#pragma warning restore 612, 618
        }
    }
}
